#!/bin/sh

case "$1" in
	start)
		start-stop-daemon -S -n aesdsocket --startas /usr/bin/aesdsocket -- -d
		;;
	stop)
		start-stop-daemon -K -n aesdsocket --signal TERM
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac
